name: Jekyll site CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: jeffreytse/jekyll-deploy-action@v0.7.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ''
          branch: 'gh-pages'
          jekyll_src: './'
          jekyll_cfg: '_config.yml'
          jekyll_baseurl: ''
          bundler_ver: '~>2.5.0'
          cname: ''
          actor: ''
          pre_build_commands: 'pacman -S --noconfirm git-lfs; git config --global http.version HTTP/1.1; git config --global http.postBuffer 524288000'
